version: '3.9'

services:
  my_local_anaconda:
    image: continuumio/anaconda3:latest
    container_name: my_local_anaconda
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - $PWD/data:/opt/data
      - $PWD/notebooks:/opt/notebooks
    ports:
      - 8888:8888
    entrypoint:
      - "/bin/sh"
      - "-c"
#      - "conda install jupyter -y --quiet && conda install openjdk -y --quiet && \
#          jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root"
      - "export DOCKER_DEFAULT_PLATFORM=linux/amd64 && \
          apt update -y && apt install -y build-essential libpq-dev && \
          conda update --all -y && \
          conda install jupyter -y --quiet && \
          conda install openjdk -y --quiet && \
          pip install psycopg2-binary --no-binary psycopg2-binary && \
          jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root"
#      -  "export DOCKER_DEFAULT_PLATFORM=linux/amd64 && \
#          conda update --all -y && \
#          conda install jupyter -y --quiet && \
#          conda install openjdk -y --quiet && \
#          pip install psycopg2-binary && \
#          jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root"

